version: '3'

services:

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s
    command: bash -c 'npm install && node index.js'    
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - proxy
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  proxy:
    build: 
      context: nginx
    container_name: proxy
    restart: always
    networks:
      - node-network
    tty: true
    ports:
      - "8081:80"

networks:
  node-network:
    driver: bridge
